// <auto-generated />
using System;
using BakeryAdmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryAdmin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208172746_Migracion")]
    partial class Migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakeryAdmin.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BakeryAdmin.Models.Caja", b =>
                {
                    b.Property<int>("CajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CajaId"));

                    b.Property<decimal?>("Cambio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoAPagar")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MontoRecibido")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NumeroCaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalDescuento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalTransaccion")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CajaId");

                    b.ToTable("Caja");
                });

            modelBuilder.Entity("BakeryAdmin.Models.ClasificadorPersona", b =>
                {
                    b.Property<int>("ClasificadorPersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClasificadorPersonaId"));

                    b.Property<string>("Acronimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolSistema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ClasificadorPersonaId");

                    b.ToTable("ClasificadorPersonas");
                });

            modelBuilder.Entity("BakeryAdmin.Models.Direccion", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DireccionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEdificio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DireccionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Direcciones");

                    b.HasData(
                        new
                        {
                            DireccionId = 1,
                            Activo = true,
                            Calle = "Chacra",
                            NombreEdificio = "Edificio Sol",
                            Numero = "123",
                            PersonaId = 1,
                            Referencia = "Cerca del parque",
                            Ubicacion = "",
                            Zona = "Centro"
                        },
                        new
                        {
                            DireccionId = 2,
                            Activo = true,
                            Calle = "Las Flores",
                            NombreEdificio = "Residencial Luna",
                            Numero = "456",
                            PersonaId = 2,
                            Referencia = "Frente a la plaza",
                            Ubicacion = "",
                            Zona = "Norte"
                        },
                        new
                        {
                            DireccionId = 3,
                            Activo = true,
                            Calle = "Av. Siempre Viva",
                            NombreEdificio = "Condominio Estrella",
                            Numero = "789",
                            PersonaId = 3,
                            Referencia = "Al lado del supermercado",
                            Ubicacion = "",
                            Zona = "Sur"
                        },
                        new
                        {
                            DireccionId = 4,
                            Activo = true,
                            Calle = "Los Pinos",
                            NombreEdificio = "Torre Cielo",
                            Numero = "321",
                            PersonaId = 4,
                            Referencia = "Detras de la iglesia",
                            Ubicacion = "",
                            Zona = "Este"
                        },
                        new
                        {
                            DireccionId = 5,
                            Activo = true,
                            Calle = "El Sol",
                            NombreEdificio = "Villa Primavera",
                            Numero = "654",
                            PersonaId = 5,
                            Referencia = "Cerca de la escuela",
                            Ubicacion = "",
                            Zona = "Oeste"
                        },
                        new
                        {
                            DireccionId = 6,
                            Activo = true,
                            Calle = "Santa Cruz",
                            NombreEdificio = "Residencial Arcoiris",
                            Numero = "987",
                            PersonaId = 6,
                            Referencia = "Frente al hospital",
                            Ubicacion = "",
                            Zona = "Centro"
                        },
                        new
                        {
                            DireccionId = 7,
                            Activo = true,
                            Calle = "Los Olivos",
                            NombreEdificio = "Edificio Horizonte",
                            Numero = "159",
                            PersonaId = 7,
                            Referencia = "Al lado del banco",
                            Ubicacion = "",
                            Zona = "Norte"
                        },
                        new
                        {
                            DireccionId = 8,
                            Activo = true,
                            Calle = "El Cedro",
                            NombreEdificio = "Condominio Mar",
                            Numero = "753",
                            PersonaId = 8,
                            Referencia = "Cerca del centro comercial",
                            Ubicacion = "",
                            Zona = "Sur"
                        },
                        new
                        {
                            DireccionId = 9,
                            Activo = true,
                            Calle = "La Paz",
                            NombreEdificio = "La Radial",
                            Numero = "852",
                            PersonaId = 9,
                            Referencia = "Detras del parque",
                            Ubicacion = "",
                            Zona = "Este"
                        },
                        new
                        {
                            DireccionId = 10,
                            Activo = true,
                            Calle = "El Roble",
                            NombreEdificio = "Villa Verde",
                            Numero = "456",
                            PersonaId = 10,
                            Referencia = "Frente a la plaza central",
                            Ubicacion = "",
                            Zona = "Oeste"
                        });
                });

            modelBuilder.Entity("BakeryAdmin.Models.Entrega", b =>
                {
                    b.Property<int>("EntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntregaId"));

                    b.Property<string>("EstadoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MinutosEstimados")
                        .HasColumnType("int");

                    b.Property<string>("NumeroEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.HasKey("EntregaId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("BakeryAdmin.Models.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<int?>("EntregaDireccionId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrden")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRecibido")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GranTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MetodoDePago")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalDescuento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrdenId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("BakeryAdmin.Models.OrdenItem", b =>
                {
                    b.Property<int>("OrdenItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenItemId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrdenItemId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenItems");
                });

            modelBuilder.Entity("BakeryAdmin.Models.PersonaBase", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Correo_Electronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumCelular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumCi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<int>("TipoPersona").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BakeryAdmin.Models.Produccion", b =>
                {
                    b.Property<int>("ProduccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduccionId"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("int");

                    b.Property<int?>("DiasValidos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroLote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProduccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("ProduccionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Producciones");

                    b.HasData(
                        new
                        {
                            ProduccionId = 1,
                            CantidadDisponible = 200,
                            CantidadProducida = 200,
                            DiasValidos = 2,
                            FechaProduccion = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "L-001",
                            NumeroProduccion = "PRD-001",
                            ProductoId = 1
                        },
                        new
                        {
                            ProduccionId = 2,
                            CantidadDisponible = 350,
                            CantidadProducida = 350,
                            DiasValidos = 2,
                            FechaProduccion = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "L-002",
                            NumeroProduccion = "PRD-002",
                            ProductoId = 2
                        },
                        new
                        {
                            ProduccionId = 3,
                            CantidadDisponible = 15,
                            CantidadProducida = 15,
                            DiasValidos = 10,
                            FechaProduccion = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "L-003",
                            NumeroProduccion = "PRD-003",
                            ProductoId = 3
                        },
                        new
                        {
                            ProduccionId = 4,
                            CantidadDisponible = 50,
                            CantidadProducida = 50,
                            DiasValidos = 5,
                            FechaProduccion = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "L-004",
                            NumeroProduccion = "PRD-004",
                            ProductoId = 4
                        },
                        new
                        {
                            ProduccionId = 5,
                            CantidadDisponible = 100,
                            CantidadProducida = 100,
                            DiasValidos = 10,
                            FechaProduccion = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "L-005",
                            NumeroProduccion = "PRD-005",
                            ProductoId = 5
                        });
                });

            modelBuilder.Entity("BakeryAdmin.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Categoria = "Panaderia",
                            Descripcion = "Pan fresco elaborado diariamente",
                            Disponible = true,
                            Fotografia = "/img/pan-frances.jpg",
                            Nombre = "Pan Frances",
                            Precio = 1.50m,
                            Unidad = "Unidad"
                        },
                        new
                        {
                            ProductoId = 2,
                            Categoria = "Panaderia",
                            Descripcion = "Clasica marraqueta crujiente",
                            Disponible = true,
                            Fotografia = "/img/marraqueta.jpg",
                            Nombre = "Marraqueta",
                            Precio = 1.00m,
                            Unidad = "Unidad"
                        },
                        new
                        {
                            ProductoId = 3,
                            Categoria = "Pasteleria",
                            Descripcion = "Torta humeda con cobertura de chocolate",
                            Disponible = true,
                            Fotografia = "/img/torta-chocolate.jpg",
                            Nombre = "Torta de Chocolate",
                            Precio = 35.00m,
                            Unidad = "Unidad"
                        },
                        new
                        {
                            ProductoId = 4,
                            Categoria = "Pasteleria",
                            Descripcion = "Rollo suave con glaseado dulce",
                            Disponible = true,
                            Fotografia = "/img/rollo-canela.jpg",
                            Nombre = "Rollo de Canela",
                            Precio = 4.50m,
                            Unidad = "Unidad"
                        },
                        new
                        {
                            ProductoId = 5,
                            Categoria = "Bebidas",
                            Descripcion = "Cafe recien pasado",
                            Disponible = true,
                            Fotografia = "/img/cafe-americano.jpg",
                            Nombre = "Cafe Americano",
                            Precio = 5.00m,
                            Unidad = "Vaso"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BakeryAdmin.Models.Cliente", b =>
                {
                    b.HasBaseType("BakeryAdmin.Models.PersonaBase");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Active = true,
                            Apellidos = "Perez",
                            Correo_Electronico = "juan.perez@email.com",
                            Fecha_Nacimiento = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Juan",
                            NumCelular = "777123456",
                            NumCi = "1234567",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 1,
                            Username = "juanp"
                        },
                        new
                        {
                            PersonaId = 6,
                            Active = true,
                            Apellidos = "Vargas",
                            Correo_Electronico = "sofia.vargas@email.com",
                            Fecha_Nacimiento = new DateTime(1994, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Sofia",
                            NumCelular = "764556677",
                            NumCi = "5566778",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 1,
                            Username = "sofiav"
                        },
                        new
                        {
                            PersonaId = 9,
                            Active = true,
                            Apellidos = "Ramirez",
                            Correo_Electronico = "jorge.ramirez@email.com",
                            Fecha_Nacimiento = new DateTime(1997, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Jorge",
                            NumCelular = "744223311",
                            NumCi = "9988776",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 1,
                            Username = "jorger"
                        });
                });

            modelBuilder.Entity("BakeryAdmin.Models.Empleado", b =>
                {
                    b.HasBaseType("BakeryAdmin.Models.PersonaBase");

                    b.Property<string>("Categoria_Licencia")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("Mobilidad")
                        .HasColumnType("bit");

                    b.Property<string>("Numero_Licencia")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Profesion")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Turno")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            PersonaId = 2,
                            Active = true,
                            Apellidos = "Lopez",
                            Correo_Electronico = "maria.lopez@email.com",
                            Fecha_Nacimiento = new DateTime(1985, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Maria",
                            NumCelular = "777987654",
                            NumCi = "7654321",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 3,
                            Username = "marial",
                            Categoria_Licencia = "C",
                            Mobilidad = false,
                            Numero_Licencia = "B54321",
                            Profesion = "Repostera",
                            Turno = "Tarde"
                        },
                        new
                        {
                            PersonaId = 5,
                            Active = true,
                            Apellidos = "Rojas",
                            Correo_Electronico = "luis.rojas@email.com",
                            Fecha_Nacimiento = new DateTime(1991, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Luis",
                            NumCelular = "789112233",
                            NumCi = "3344556",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 3,
                            Username = "luisr",
                            Categoria_Licencia = "C",
                            Mobilidad = false,
                            Numero_Licencia = "E33333",
                            Profesion = "Cajero",
                            Turno = "Noche"
                        },
                        new
                        {
                            PersonaId = 7,
                            Active = true,
                            Apellidos = "Castro",
                            Correo_Electronico = "miguel.castro@email.com",
                            Fecha_Nacimiento = new DateTime(1988, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Miguel",
                            NumCelular = "701223344",
                            NumCi = "2233445",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 3,
                            Username = "miguelc",
                            Categoria_Licencia = "C",
                            Mobilidad = true,
                            Numero_Licencia = "G55555",
                            Profesion = "Chofer",
                            Turno = "Ma�ana"
                        },
                        new
                        {
                            PersonaId = 10,
                            Active = true,
                            Apellidos = "Suarez",
                            Correo_Electronico = "elena.suarez@email.com",
                            Fecha_Nacimiento = new DateTime(1990, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Elena",
                            NumCelular = "755443322",
                            NumCi = "1122334",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 3,
                            Username = "elenas",
                            Categoria_Licencia = "B",
                            Mobilidad = true,
                            Numero_Licencia = "J88888",
                            Profesion = "Supervisora",
                            Turno = "Noche"
                        });
                });

            modelBuilder.Entity("BakeryAdmin.Models.Proveedor", b =>
                {
                    b.HasBaseType("BakeryAdmin.Models.PersonaBase");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            PersonaId = 3,
                            Active = true,
                            Apellidos = "Gonzales",
                            Correo_Electronico = "carlos.gonzales@email.com",
                            Fecha_Nacimiento = new DateTime(1992, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Carlos",
                            NumCelular = "700112233",
                            NumCi = "4567890",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 2,
                            Username = "carlosg"
                        });
                });

            modelBuilder.Entity("BakeryAdmin.Models.Vendedor", b =>
                {
                    b.HasBaseType("BakeryAdmin.Models.PersonaBase");

                    b.HasDiscriminator().HasValue(4);

                    b.HasData(
                        new
                        {
                            PersonaId = 4,
                            Active = true,
                            Apellidos = "Torrez",
                            Correo_Electronico = "ana.torrez@email.com",
                            Fecha_Nacimiento = new DateTime(1996, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Ana",
                            NumCelular = "720334455",
                            NumCi = "9081726",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 4,
                            Username = "anat"
                        },
                        new
                        {
                            PersonaId = 8,
                            Active = true,
                            Apellidos = "Mendoza",
                            Correo_Electronico = "patricia.mendoza@email.com",
                            Fecha_Nacimiento = new DateTime(1993, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Patricia",
                            NumCelular = "713445566",
                            NumCi = "6677889",
                            PasswordHash = "hashedpassword",
                            TipoPersona = 4,
                            Username = "patriciam"
                        });
                });

            modelBuilder.Entity("BakeryAdmin.Models.Direccion", b =>
                {
                    b.HasOne("BakeryAdmin.Models.PersonaBase", "Persona")
                        .WithMany("Direcciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BakeryAdmin.Models.Orden", b =>
                {
                    b.HasOne("BakeryAdmin.Models.PersonaBase", "Cliente")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BakeryAdmin.Models.OrdenItem", b =>
                {
                    b.HasOne("BakeryAdmin.Models.Orden", "Orden")
                        .WithMany("Items")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryAdmin.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BakeryAdmin.Models.Produccion", b =>
                {
                    b.HasOne("BakeryAdmin.Models.Producto", "Producto")
                        .WithMany("Producciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BakeryAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BakeryAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BakeryAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BakeryAdmin.Models.Orden", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BakeryAdmin.Models.PersonaBase", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("BakeryAdmin.Models.Producto", b =>
                {
                    b.Navigation("Producciones");
                });
#pragma warning restore 612, 618
        }
    }
}
